language: node_js
node_js:
  - "node"
  - "0.12"
  - "iojs"
  - "iojs-v1.0.4"
notifications:
  email: false
before_script:
  - "export DISPLAY=:99.0"

  - sh -e /etc/init.d/xvfb start
  - nohup bash -c "./nodemodules/protractor/bin/webdriver-manager start 2>&1 &"
  - sleep 5

script:
  - npm test
